apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kerariadne/GitOps_Projects.git'
    targetRevision: HEAD
    path: 'EKS_Cluster'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
