name: Deploy to EKS and ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-west-2 --name gitops-cluster

      - name: Check if the EKS cluster exists
        id: check_cluster
        run: |
          aws eks describe-cluster --name gitops-cluster --region us-west-2 || echo "Cluster does not exist"

      - name: Create EKS cluster if it does not exist
        if: steps.check_cluster.outputs.result == 'Cluster does not exist'
        run: |
          eksctl create cluster --name gitops-cluster --region us-west-2 --nodegroup-name linux-nodes --node-type t3.medium --nodes 2 --nodes-min 2 --nodes-max 4 --managed

      - name: Install ArgoCD CRDs
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/crds.yaml

      - name: Install ArgoCD (if not already installed)
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Deploy app manifests
        run: |
          kubectl apply -f EKS_Cluster/app-deployment.yaml
          kubectl apply -f EKS_Cluster/app-service.yaml
          kubectl apply -f EKS_Cluster/argocd-app.yaml
