name: Deploy to EKS with Argo CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-west-2 --name gitops-cluster

      - name: Create Argo CD namespace if not exists
        run: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

      - name: Install Argo CD
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Patch Argo CD service to LoadBalancer
        run: |
          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

      - name: Wait for Argo CD server to be ready
        run: |
          kubectl wait --for=condition=available deployment/argocd-server -n argocd --timeout=180s

      - name: Apply app deployment and service
        run: |
          kubectl apply -f EKS_Cluster/app-deployment.yaml
          kubectl apply -f EKS_Cluster/app-service.yaml

      - name: Install Argo CD CRDs
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/crds.yaml || true

      - name: Apply Argo CD Application
        run: |
          kubectl apply -f EKS_Cluster/argocd-app.yaml
